# Generated by Django 4.2.5 on 2025-03-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_summary', '0001_initial'),
        ('overtimebase', '0001_initial'),
        ('overtimehours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimehours',
            name='attendancesummary_id',
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='attendancesummary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_summary.attendancesummary'),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='backwage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='nightdiff',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='otbase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtimebase.overtimebase'),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='regularholiday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='regularot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='restday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overtimehours',
            name='specialholiday',
            field=models.IntegerField(default=0),
        ),
    ]
