# Generated by Django 4.2.5 on 2025-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimehours', '0002_remove_overtimehours_attendancesummary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimehours',
            name='biweek_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
