# Generated by Django 4.2.5 on 2025-03-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimehours', '0003_overtimehours_biweek_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimehours',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='overtimehours',
            name='undertime',
            field=models.IntegerField(default=0),
        ),
    ]
