# Generated by Django 4.2.5 on 2025-03-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtimehours', '0005_overtimehours_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimehours',
            name='otbase',
        ),
    ]
